### ISSUE TITLE
The new libsecret code does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by mgedmin** [gtimelog/gtimelog#156]
Testing on Ubuntu 16.04 reveals a problem:

- open email preferences
- type in something in the SMTP username and password fields
- press Enter or Tab

You'll see this on the console:

    AttributeError: 'gi.repository.Secret' object has no attribute 'get_schema'

This is because Secret.get_schema() was introduced in libsecret 0.18.6, but Ubuntu 16.04 has libsecret 0.18.4.

I'm not sure what to do.  I'm considering not supporting Ubuntu 16.04.

**Comment by andrewshadura** [comment]
It used to be shipped in `SecretUnstable`. I think you can try importing it from there first.

**Comment by andrewshadura** [comment]
Actually, I’m wrong. GNOME/libsecret@b738c9f introduced it.
